name: 自动打包并上传Release

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置压缩包名称
        id: set_filename
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          echo "FILENAME=data${TIMESTAMP}.zip" >> $GITHUB_ENV

      - name: 打包文件
        run: |
          zip -r ${{ env.FILENAME }} . \
            -x "*.git*" \
            -x "*.github/workflows/*" \
            -x "*.zip"

      - name: 上传到Release
        uses: softprops/action-gh-release@v2
        with:
          name: 自动打包-${{ env.FILENAME }}
          tag_name: ${{ env.FILENAME }}
          files: ${{ env.FILENAME }}
        env:
          GITHUB_TOKEN: ${{ CUSTOM_GITHUB_TOKEN }}  # 替换为自定义密钥名称

      - name: 保留最新3个Release
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ CUSTOM_GITHUB_TOKEN }}  # 同样替换为自定义密钥名称
