name: 自动打包并上传Release

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置压缩包名称
        id: set_filename
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          echo "FILENAME=data${TIMESTAMP}.zip" >> $GITHUB_ENV  # 换回zip格式

      - name: 打包文件（使用zip）
        run: |
          # 使用zip打包，排除指定目录和文件
          zip -r ${{ env.FILENAME }} . \
            -x ".git/" -x ".gitignore" -x ".github/workflows/" -x "*.zip"  # 排除规则适配zip

      - name: 上传到Release
        uses: softprops/action-gh-release@v2
        with:
          name: 自动打包-${{ env.FILENAME }}
          tag_name: ${{ env.FILENAME }}
          files: ${{ env.FILENAME }}
          body: |
                ### 本仓库是azerothcore playerbot分支的地图数据，包含以下内容：
                   - map
                   - mmap
                   - dbc
                   - vmap
                   - Cameras
                   - 增加中文dbc解决机器人的技能问题
                   - 解压使用rar或zip
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: 保留最新2个Release
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 2
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
