name: 自动打包并上传Release

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置压缩包名称
        id: set_filename
        run: |
          TIMESTAMP=$(date +"%Y%m%d%H%M%S")
          echo "FILENAME=data${TIMESTAMP}.zip" >> $GITHUB_ENV

      - name: 读取Readme内容作为Release描述
        id: read_readme
        run: |
          # 读取Readme.md内容，处理特殊字符（如换行符）
          README_CONTENT=$(cat README.md | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/\\n/g')
          echo "README_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$README_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: 打包文件
        run: |
          zip -r ${{ env.FILENAME }} . \
            -x ".git/" -x ".gitignore" -x ".github/workflows/" -x "*.zip"  # 优化排除规则

      - name: 上传到Release
        uses: softprops/action-gh-release@v2
        with:
          name: 自动打包-${{ env.FILENAME }}
          tag_name: ${{ env.FILENAME }}
          files: ${{ env.FILENAME }}
          body: ${{ env.README_CONTENT }}  # 这里填入Readme内容作为Release描述
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: 保留最新3个Release
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
