name: Delete_Old_Workflows

on:
  workflow_dispatch:
  schedule:
    - cron: 0 19 * * *

jobs:
  Clean-Workflows:
    runs-on: ubuntu-22.04
    permissions:
      actions: write

    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.DEL_GITHUB_TOKEN }}
          keep_minimum_runs: 2
          retain_days: 0
