name: Delete_Old_Workflows_Keep_1Day

on:
  workflow_dispatch:  # 支持手动触发
  schedule:
    - cron: 0 19 * * *  # 每天UTC 19点自动运行（可根据需求调整时间）

jobs:
  Clean-Workflows:
    runs-on: ubuntu-22.04
    permissions:
      actions: write  # 授予删除工作流运行记录的权限

    steps:
      - name: Delete workflow runs older than 1 day
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.DEL_GITHUB_TOKEN }}
          retain_days: 1  # 保留最近1天的记录
          keep_minimum_runs: 0  # 不强制保留最小数量（仅按天数保留）
